"""Stable domain and infrastructure errors."""


class VibeMuxError(Exception):
    """Base error for user-facing failures."""


class ConfigurationError(VibeMuxError): ...
class NotInitializedError(VibeMuxError): ...
class UnsupportedPlatformError(VibeMuxError): ...
class GitRepositoryError(VibeMuxError): ...
class DirtyRepositoryError(GitRepositoryError): ...
class WorktreeError(VibeMuxError): ...
class TerminalBackendError(VibeMuxError): ...
class TerminalNotAvailableError(TerminalBackendError): ...
class TerminalResourceMismatchError(TerminalBackendError): ...
class HarnessNotFoundError(VibeMuxError): ...
class HarnessConfigurationError(VibeMuxError): ...
class ExecutionBackendError(VibeMuxError): ...
class InvalidStateTransitionError(VibeMuxError): ...
class ResourceSafetyError(VibeMuxError): ...
class StorageError(VibeMuxError): ...
class ReconciliationError(VibeMuxError): ...
class GitHubPublicationError(VibeMuxError): ...
