"""Generate WezTerm and tmux appearance configuration from the shared
theme palettes.

Generation only: this module never writes files or mutates terminal
state. The CLI prints the snippet and the user opts in by pasting it
into their WezTerm config or sourcing it from tmux. The generated pane
chrome (background, foreground, cursor, selection, split/border)
matches the VibeMux GUI palette; the ANSI 16-color ramp is intentionally
left to the terminal's base scheme so the same snippet stays consistent
across backends.
"""

from __future__ import annotations

from vibemux.theme import ThemePalette, parse_hex_rgb

# The standard xterm-256 palette: the 16-color base ramp, the 6x6x6
# color cube, then the grayscale ramp.
_BASE_RAMP: tuple[tuple[int, int, int], ...] = (
    (0, 0, 0),
    (205, 0, 0),
    (0, 205, 0),
    (205, 205, 0),
    (0, 0, 238),
    (205, 0, 205),
    (0, 205, 205),
    (229, 229, 229),
    (127, 127, 127),
    (255, 0, 0),
    (0, 255, 0),
    (255, 255, 0),
    (92, 92, 255),
    (255, 0, 255),
    (0, 255, 255),
    (255, 255, 255),
)
_CUBE_LEVELS: tuple[int, ...] = (0, 95, 135, 175, 215, 255)


def xterm256_palette() -> list[tuple[int, int, int]]:
    """The 256 standard xterm palette entries as ``(r, g, b)`` triples."""
    palette: list[tuple[int, int, int]] = list(_BASE_RAMP)
    for red_index in range(6):
        for green_index in range(6):
            for blue_index in range(6):
                palette.append(
                    (
                        _CUBE_LEVELS[red_index],
                        _CUBE_LEVELS[green_index],
                        _CUBE_LEVELS[blue_index],
                    )
                )
    palette.extend((8 + 10 * step,) * 3 for step in range(24))
    return palette


def xterm256_nearest(rgb: tuple[int, int, int]) -> int:
    """The nearest xterm-256 index by squared RGB distance."""
    palette = xterm256_palette()
    red, green, blue = rgb
    best_index = 0
    best_distance: int | None = None
    for index, (candidate_red, candidate_green, candidate_blue) in enumerate(palette):
        distance = (
            (red - candidate_red) ** 2
            + (green - candidate_green) ** 2
            + (blue - candidate_blue) ** 2
        )
        if best_distance is None or distance < best_distance:
            best_index = index
            best_distance = distance
    return best_index


def _colour(index: int) -> str:
    return f"colour{index}"


def _tmux_color(palette: ThemePalette, field: str) -> str:
    rgb = parse_hex_rgb(getattr(palette, field))
    if rgb is None:
        raise ValueError(f"palette {palette.name} has invalid hex for {field}")
    return _colour(xterm256_nearest(rgb))


def render_wezterm_scheme(palette: ThemePalette) -> str:
    """Render the palette as a WezTerm ``config.colors`` table (lua)."""
    return (
        f"-- VibeMux theme: {palette.name}\n"
        f"-- Generated by `vibemux theme --backend wezterm --theme {palette.name}`.\n"
        "-- Paste as `config.colors = { ... }` or merge it into wezterm.lua.\n"
        "-- The ANSI 16-color ramp is intentionally left to your base scheme.\n"
        "return {\n"
        "  colors = {\n"
        f'    foreground = "{palette.terminal_fg}",\n'
        f'    background = "{palette.terminal_bg}",\n'
        f'    cursor_bg = "{palette.terminal_cursor}",\n'
        f'    cursor_fg = "{palette.terminal_bg}",\n'
        f'    selection_bg = "{palette.surface_alt}",\n'
        f'    selection_fg = "{palette.terminal_fg}",\n'
        f'    split = "{palette.border}",\n'
        "  },\n"
        "}\n"
    )


def render_tmux_theme(palette: ThemePalette) -> str:
    """Render the palette as tmux ``set -g`` options (colour<N> forms)."""
    status_background = _tmux_color(palette, "terminal_bg")
    status_foreground = _tmux_color(palette, "terminal_fg")
    border = _tmux_color(palette, "border")
    accent = _tmux_color(palette, "accent")
    return (
        f"# VibeMux theme: {palette.name}\n"
        f"# Generated by `vibemux theme --backend tmux --theme {palette.name}`.\n"
        "# Source from ~/.tmux.conf or apply with `tmux source-file <path>`.\n"
        "# colour<N> values are the nearest xterm-256 entries to the VibeMux\n"
        "# GUI palette; the ANSI 16-color ramp is intentionally left untouched.\n"
        f'set -g status-style "bg={status_background},fg={status_foreground}"\n'
        f'set -g pane-border-style "fg={border}"\n'
        f'set -g pane-active-border-style "fg={accent}"\n'
        f'set -g message-style "bg={accent},fg={status_background}"\n'
        f'set -g mode-style "bg={accent},fg={status_background}"\n'
    )
